# Generated by Django 5.2.1 on 2025-05-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_address',
            field=models.TextField(default='Soweto'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_latitude',
            field=models.FloatField(default=-26.2673),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_longitude',
            field=models.FloatField(default=-26.2673),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='estimated_dropoff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_address',
            field=models.TextField(default='Roodepoort'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_latitude',
            field=models.FloatField(default=-26.137657),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_longitude',
            field=models.FloatField(default=27.805727),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='actual_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='dropoff_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_rides', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='estimated_fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_rides', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride_type',
            field=models.CharField(choices=[('home_to_school', 'Home to School'), ('school_to_home', 'School to Home')], default='home_to_school', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
